**Lab 3.0 – Handling UI Events   **

**Overview: **

In this lab you add code to handle a UI event. As the user enters text for their update, the
activity should display the number of characters left to use (updates are a maximum of 140 characters).

**Steps**

 .1) Add a handler for the "Tweet" button.

When the user presses the "Tweet" button, write a message to the log file.

 .1a) Create an +onClick+ method to handle the button press.  The method should
 take a +View+ as an arguement.

[source]
----
private static final String TAG = StatusActivity.class.getSimpleName();

public void onClick(View v) {
    Log.d(TAG, "Button Clicked");
}
----

 .1b) Add an +onClick+ attribute to the status activity layout in the <Button> element.

[source]
----
android:onClick="onClick"
----

The value of the attribute must correspond to the name of the method in the activity.

Run the app and verify that the onClick listener is being called.

 .1c) Implement the +onClick+ listener in +StatusActivity.java+.

[source]
----
public class StatusActivity extends Activity implements OnClickListener {
----

 .1d) Assign the onClick Listener to the button

[source]
----
// Find Button object
Button myButton = (Button) findViewById(R.id.status_button_tweet);

// Register activity as click listener
myButton.setOnClickListener(this);
----

Note:  Remove the +onClick+ attribute in "status_activity.xml".  It is now redundant.

 .2) Add a TextView with id +status_text_count+ to activity layout. This will be in file +res/layout/activity_status.xml+

Hint: don’t forget to update landscape layout as well!

[source]
----
<TextView
    android:id="@+id/status_text_count"
    style="@style/font_general"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_alignRight="@+id/status_button_tweet"
    android:layout_below="@+id/status_button_tweet"
    android:text="140" />
----

 .3) Add a TextWatcher listener to the status text field and update textCount as the user types.

[source]
----
private TextView mTextCount;

mTextStatus.addTextChangedListener(new TextWatcher() {

  	@Override
  	public void afterTextChanged(Editable s) {
    		int count = 140 - s.length();
    		mTextCount.setText(Integer.toString(count));
  	}

  	@Override
  	public void beforeTextChanged(CharSequence s, int start, int count, int after) {
  	}

  	@Override
  	public void onTextChanged(CharSequence s, int start, int before, int count) {
  	}

});
----

Question 1: Is it necessary to provide overrides for +beforeTextChanged+ and
+onTextChanged+ since they have no code?

Question 2: Should the code be added to +onTextChanged+ instead of +afterTextChanged+?

 .4) If the update exceeds 140 characters then make the count red as a warning.

[source]
----
 if (count < 50) {
   mTextCount.setTextColor(Color.RED);
 } else {
   mTextCount.setTextColor(mDefaultColor);
 }
----
