**Lab 6.0 – Create PrefsActivity and wire it to the app   **

**Overview: **

In this lab you will create a new activity that will allow a user to specify and
save configuration information.

**Steps**

 .1)  Create an empty Preference activity.

Add menu button to launch it.

1. Create a Preference resource file called settings.xml.

This will describe the various setting properties, including their name and description.

[source]
----
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android" >

    <EditTextPreference
        android:key="username"
        android:summary="@string/username_summary"
        android:title="@string/username" />
    <EditTextPreference
        android:inputType="textPassword"
        android:key="password"
        android:summary="@string/password_summary"
        android:title="@string/password" />

    <ListPreference
        android:entries="@array/interval_names"
        android:entryValues="@array/interval_values"
        android:key="interval"
        android:summary="@string/interval_summary"
        android:title="@string/interval" />

</PreferenceScreen>
----


2. Implement the SettingsActivity.java file that inflates that resource file.

[source]
----
public class SettingsActivity extends SubActivity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		// Check if this activity was created before
		if (savedInstanceState == null) {
			// Create a fragment
			SettingsFragment fragment = new SettingsFragment();
			getFragmentManager()
					.beginTransaction()
					.add(android.R.id.content, fragment, fragment.getClass().getSimpleName()).commit();
		}
	};
}
----

3. Create the settings fragment

[source]
----
public class SettingsFragment extends PreferenceFragment implements
		OnSharedPreferenceChangeListener {
	private SharedPreferences prefs;

	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		addPreferencesFromResource(R.xml.settings);
	}

	@Override
	public void onStart() {
		super.onStart();
		prefs = PreferenceManager.getDefaultSharedPreferences(getActivity());
		prefs.registerOnSharedPreferenceChangeListener(this);
	}

	@Override
	public void onStop() {
		super.onStop();
		prefs.unregisterOnSharedPreferenceChangeListener(this);
	}

	@Override
	public void onSharedPreferenceChanged(SharedPreferences sharedPreferences,
			String key) {
		getActivity().sendBroadcast( new Intent("com.marakana.android.yamba.action.UPDATED_INTERVAL") );
	}
}
----


3. Register this new activity with the AndroidManifest.xml file.

[source]
----
<activity
    android:name="com.marakana.android.yamba.SettingsActivity"
    android:label="@string/action_settings" >
</activity>
----

4. Provide a way to start that activity from the rest of the application.

  a. menu




  	// Called to lazily initialize the action bar
  	@Override
  	public boolean onCreateOptionsMenu(Menu menu) {
  		// Inflate the menu; this adds items to the action bar if it is present.
  		getMenuInflater().inflate(R.menu.main, menu);
  		return true;
  	}


  b. menu selection



	// Called every time user clicks on an action
	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		switch (item.getItemId()) {
		case R.id.action_settings:
			startActivity(new Intent(this, SettingsActivity.class));
			return true;
		case R.id.action_tweet:
			startActivity(new Intent("com.marakana.android.yamba.action.tweet"));
			return true;
		default:
			return false;
		}
	}


	c.  Create menu declaration

<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context=".MainActivity" >
    <item android:id="@+id/action_settings"
        android:title="@string/action_settings"
        android:orderInCategory="100"
        android:showAsAction="never" />
</menu>
